/* Current MVP copy in all six supported languages. No gameplay dependencies. */
window.BalloroPlayerCopy = {
  "en": {
    "balance": "Balance",
    "changeAvatar": "Change Avatar",
    "sound": "Game SFX",
    "music": "Music",
    "animations": "Animations",
    "language": "Language",
    "gameRules": "Game Rules",
    "rules": "Rules",
    "topUpTitle": "Top Up Balance",
    "topUpText": "Add any amount to continue playing.",
    "amount": "Amount",
    "topUp": "TOP UP",
    "cancel": "CANCEL",
    "totalHistory": "HISTORY:",
    "roundHistory": "Round History",
    "todayTopWins": "TODAY TOP WINS",
    "riskLevel": "RISK",
    "lines": "LINES",
    "low": "Low",
    "normal": "Normal",
    "high": "High",
    "pucks": "BALLS",
    "auto": "AUTO",
    "bet": "BET",
    "wait": "WAIT",
    "round": "ROUND",
    "livePlayers": "LIVE PROTOTYPE PLAYERS",
    "liveSubtitle": "LOCAL SIMULATION · SHARED GAME MATH",
    "player": "Player",
    "type": "Type",
    "riskLines": "Risk / Lines",
    "result": "Result",
    "payout": "Payout",
    "status": "Status",
    "lost": "Lost",
    "win": "Win",
    "avatar": "Avatar",
    "showFullWinners": "Show full today top wins",
    "showTopWinner": "Show only today's top win",
    "settings": "Settings",
    "volume": "Volume",
    "audioSection": "Audio",
    "playSection": "Play",
    "profileSection": "Profile",
    "moreSection": "More",
    "quickPlay": "Quick Play · ×3",
    "quickHint": "Faster ball movement. One launch every 0.5 s instead of 1 s; bonus preparation keeps its pace.",
    "openHistory": "My shots",
    "openTop": "Daily top & demo wins",
    "changeNickname": "Change nickname",
    "yourNickname": "Your nickname",
    "nicknameHint": "1–20 characters. Your nickname appears in the daily top.",
    "nicknameRequired": "Enter a nickname",
    "save": "Save",
    "done": "Done",
    "betPerBall": "Stake per ball · USD",
    "totalBet": "Total stake",
    "launchBall": "Launch one ball",
    "controls": "Game controls",
    "autoCount": "Number of paid shots",
    "autoHint": "Tap Autoplay again to stop new launches. Balls already in play will finish.",
    "startAuto": "Start autoplay",
    "noHistory": "No completed shots yet",
    "close": "Close",
    "time": "Time",
    "profit": "Net result",
    "demoWins": "Wins · DEMO",
    "backToGame": "Back to game",
    "collapse": "Collapse",
    "expand": "Expand",
    "bonusHelpLabel": "How this bonus works",
    "bonusDemo": "Bonus demonstration",
    "demoNote": "Illustration only · not a game result",
    "pauseDemo": "Pause animation",
    "playDemo": "Play animation",
    "stepCapture": "Capture",
    "stepPrepare": "Prepare",
    "stepRelease": "Release",
    "colorsTitle": "Multiplier colours",
    "greenLabel": "Green · up to 1x",
    "yellowLabel": "Yellow · above 1x, below 10x",
    "redLabel": "Red · 10x or more",
    "purpleLabel": "Purple · X10 BOOST",
    "multiplierTable": "Current multipliers",
    "mainField": "Main field",
    "leftRoom": "Left room",
    "rightRoom": "Right room",
    "loading": "Loading Balloro X",
    "fieldLabel": "Balloro X game field",
    "ruleLaunchTitle": "One stake — one ball",
    "ruleLaunchText": "Choose your stake and 5, 7 or 9 lines. Tap Spin to launch one ball. Hold it for new launches every second; every 0.5 seconds in Quick Play.",
    "ruleWinsTitle": "Stopping on a multiplier",
    "ruleWinsText": "The payout is the original stake × the stopping cell multiplier. A return below your stake is a partial return, not a net win. Red and purple results play celebration music and flashing walls.",
    "rulePocketTitle": "X3 BALLS · green pocket",
    "rulePocketFieldText": "A ball is pulled into the green pocket on the left. The cactus rises and flies to its counter. One symbol is enough: after preparation, the pocket releases three white balls. Their payouts are added together.",
    "ruleBoostTitle": "X10 BOOST · purple pocket",
    "ruleBoostText": "The top pocket collects one diamond. After it reaches the counter and other balls stop, the field and both rooms turn purple. Then the ball launches; its wins and those of its bonus descendants are multiplied by 10. The effect lasts until the whole chain finishes.",
    "ruleMultiTitle": "EX MULTI · yellow pocket",
    "ruleMultiText": "The right pocket collects one star. After it reaches the counter and other balls stop, moving highlights select cells and temporarily multiply their values by 10. The pocket releases the ball; a boosted payout requires stopping on an enhanced cell.",
    "ruleLuckyTitle": "LUCKY SHOT · red pocket",
    "ruleLuckyText": "The bottom pocket collects one flame. The ball blinks in the pocket while preparing, then sinks and appears between the two secret rooms without blinking. The rooms flash, one is selected and the ball launches into it. Every cell in both rooms pays; X10 BOOST also applies there.",
    "ruleFieldTitle": "5, 7 or 9 lines",
    "ruleFieldText": "Lines change the cells and their multipliers, not the stake per ball. See the current table below. Configuration can only change after active play finishes.",
    "ruleAutoTitle": "Autoplay",
    "ruleAutoText": "Choose the number of paid shots and start autoplay. Balls launch every 1 s, or every 0.5 s in Quick Play. Bonus preparation and play pause new bets. Bonus launches do not charge a new stake.",
    "rulesAboutTitle": "Good to know",
    "rulesAboutIntro": "Field values show the payout as a multiple of the original stake. Colour identifies the multiplier tier; it does not change the payout.",
    "rulesHowToWinTitle": "Payouts and colours",
    "rulesHowToWinText": "Green: up to 1x. Yellow: above 1x but below 10x. Red: 10x or more. Purple: active X10 BOOST. Only red and purple results trigger a big-win celebration. All bonus descendants belong to their original paid stake.",
    "rulesRtpTitle": "Theoretical RTP",
    "rulesRtpText": "This MVP has a theoretical RTP of 97.45% at 5, 7 and 9 lines, including bonus chains. It is an average over many stakes, not a promise for a session. Probabilities do not adapt to your balance or previous wins.",
    "rulesMaxWinTitle": "Field and secret rooms",
    "rulesMaxWinText": "The table shows normal values without boosts. X10 BOOST multiplies values by 10; EX MULTI temporarily boosts selected cells by another 10. A single-cell multiplier is not a cap on the total payout of a bonus chain.",
    "rulesVolatilityTitle": "Bonus queues",
    "rulesVolatilityText": "New bets lock when bonus collection begins. Already launched balls finish moving. Bonuses resolve in order: green → yellow → red → purple. The number above a pocket counts waiting balls, excluding the current ball. A continuous queue sends its symbol to the counter only once.",
    "rulesDisclosureTitle": "Test build",
    "rulesDisclosureText": "This is a local MVP with a demo balance, not real-money play. Outcomes use fixed probabilities, followed by an existing physically computed trajectory. Animation and speed do not change payouts. Other-player tables are labelled as demo."
  },
  "ru": {
    "balance": "Баланс",
    "changeAvatar": "Сменить аватар",
    "sound": "Звуки игры",
    "music": "Музыка",
    "animations": "Анимации",
    "language": "Язык",
    "gameRules": "Правила игры",
    "rules": "Правила",
    "topUpTitle": "Пополнить баланс",
    "topUpText": "Добавьте любую сумму, чтобы продолжить игру.",
    "amount": "Сумма",
    "topUp": "ПОПОЛНИТЬ",
    "cancel": "ОТМЕНА",
    "totalHistory": "ИСТОРИЯ:",
    "roundHistory": "История раундов",
    "todayTopWins": "ТОП ДНЯ",
    "riskLevel": "РИСК",
    "lines": "ЛИНИИ",
    "low": "Низкий",
    "normal": "Средний",
    "high": "Высокий",
    "pucks": "ШАРЫ",
    "auto": "АВТО",
    "bet": "СТАВКА",
    "wait": "ЖДАТЬ",
    "round": "РАУНД",
    "livePlayers": "ИГРОКИ ПРОТОТИПА",
    "liveSubtitle": "ЛОКАЛЬНАЯ СИМУЛЯЦИЯ · ОБЩАЯ МАТЕМАТИКА",
    "player": "Игрок",
    "type": "Тип",
    "riskLines": "Риск / Линии",
    "result": "Результат",
    "payout": "Выплата",
    "status": "Статус",
    "lost": "Проигрыш",
    "win": "Выигрыш",
    "avatar": "Аватар",
    "showFullWinners": "Показать 10 лучших выигрышей сегодня",
    "showTopWinner": "Показать только лучший выигрыш сегодня",
    "settings": "Настройки",
    "volume": "Громкость",
    "audioSection": "Звук",
    "playSection": "Игра",
    "profileSection": "Профиль",
    "moreSection": "Дополнительно",
    "quickPlay": "Быстрая игра · ×3",
    "quickHint": "Шары движутся быстрее. Запуск раз в 0,5 с вместо 1 с; подготовка бонусов не ускоряется.",
    "openHistory": "Мои броски",
    "openTop": "Топ дня и демо-выигрыши",
    "changeNickname": "Сменить ник",
    "yourNickname": "Ваш ник",
    "nicknameHint": "От 1 до 20 символов. Ник отображается в топе дня.",
    "nicknameRequired": "Введите ник",
    "save": "Сохранить",
    "done": "Готово",
    "betPerBall": "Ставка на шар · USD",
    "totalBet": "Общая ставка",
    "launchBall": "Запустить один шар",
    "controls": "Управление игрой",
    "autoCount": "Количество платных бросков",
    "autoHint": "Нажмите автоигру ещё раз, чтобы остановить новые запуски. Шары на поле закончат движение.",
    "startAuto": "Начать автоигру",
    "noHistory": "Завершённых бросков пока нет",
    "close": "Закрыть",
    "time": "Время",
    "profit": "Чистый результат",
    "demoWins": "Выигрыши · ДЕМО",
    "backToGame": "Вернуться к игре",
    "collapse": "Свернуть",
    "expand": "Развернуть",
    "bonusHelpLabel": "Как работает этот бонус",
    "bonusDemo": "Демонстрация бонуса",
    "demoNote": "Схематичный пример · не игровой результат",
    "pauseDemo": "Остановить анимацию",
    "playDemo": "Включить анимацию",
    "stepCapture": "Подбор",
    "stepPrepare": "Подготовка",
    "stepRelease": "Выстрел",
    "colorsTitle": "Цвета множителей",
    "greenLabel": "Зелёный · до 1x",
    "yellowLabel": "Жёлтый · больше 1x, меньше 10x",
    "redLabel": "Красный · от 10x",
    "purpleLabel": "Фиолетовый · X10 BOOST",
    "multiplierTable": "Текущие множители",
    "mainField": "Основной ромб",
    "leftRoom": "Левая СК",
    "rightRoom": "Правая СК",
    "loading": "Загрузка Balloro X",
    "fieldLabel": "Игровое поле Balloro X",
    "ruleLaunchTitle": "Одна ставка — один шар",
    "ruleLaunchText": "Выберите ставку и 5, 7 или 9 линий. Нажмите спин для запуска одного шара. Удерживайте кнопку для новых запусков раз в секунду; в быстрой игре — раз в 0,5 секунды.",
    "ruleWinsTitle": "Остановка на множителе",
    "ruleWinsText": "Выплата равна исходной ставке × множитель ячейки остановки. Возврат меньше ставки — это частичный возврат, а не чистый выигрыш. Красные и фиолетовые результаты сопровождаются музыкой и миганием стенок.",
    "rulePocketTitle": "X3 BALLS · зелёная луза",
    "rulePocketFieldText": "Шар притягивается в зелёную лузу слева. Кактус поднимается и летит в счётчик. Одного символа достаточно: после подготовки луза выпускает три белых шара. Их выплаты складываются.",
    "ruleBoostTitle": "X10 BOOST · фиолетовая луза",
    "ruleBoostText": "Верхняя луза подбирает один алмаз. После его прилёта в счётчик и остановки остальных шаров поле и обе СК становятся фиолетовыми. Затем шар вылетает; его выигрыши и выигрыши его бонусных потомков умножаются на 10. Эффект сохраняется до завершения всей цепочки.",
    "ruleMultiTitle": "EX MULTI · жёлтая луза",
    "ruleMultiText": "Луза справа подбирает одну звезду. После её прилёта и остановки остальных шаров подсветка выбирает ячейки и временно умножает их значения на 10. Луза выпускает шар: повышенный выигрыш будет только при остановке на усиленной ячейке.",
    "ruleLuckyTitle": "LUCKY SHOT · красная луза",
    "ruleLuckyText": "Нижняя луза подбирает один огонёк. Во время подготовки шар мигает в лузе, затем проваливается и появляется между двумя секретными комнатами (СК) уже без мигания. Комнаты мигают, выбирается одна из них, затем туда выстреливает шар. В обеих СК платят все ячейки; X10 BOOST действует и здесь.",
    "ruleFieldTitle": "5, 7 или 9 линий",
    "ruleFieldText": "Число линий меняет ячейки и множители, но не ставку на шар. Смотрите текущую таблицу ниже. Конфигурацию можно менять только после завершения активной игры.",
    "ruleAutoTitle": "Автоигра",
    "ruleAutoText": "Выберите число платных бросков и запустите автоигру. Новые шары вылетают раз в 1 с, в быстрой игре — раз в 0,5 с. Подготовка и отыгрыш бонуса приостанавливают новые ставки. Бонусные выстрелы не списывают новую ставку.",
    "rulesAboutTitle": "Важно знать",
    "rulesAboutIntro": "Значения на поле показывают выплату в долях исходной ставки. Цвет обозначает уровень множителя, но сам по себе не меняет выплату.",
    "rulesHowToWinTitle": "Выплаты и цвета",
    "rulesHowToWinText": "Зелёный: до 1x. Жёлтый: больше 1x, но меньше 10x. Красный: 10x и выше. Фиолетовый: активный X10 BOOST. Только красные и фиолетовые результаты запускают супервыигрыш. Выплаты всех бонусных потомков относятся к их исходной платной ставке.",
    "rulesRtpTitle": "Теоретический RTP",
    "rulesRtpText": "RTP текущей MVP-версии — 97,45% на 5, 7 и 9 линиях, с учётом цепочек бонусов. Это средний возврат на большом числе ставок, не обещание результата одной сессии. Вероятности не подстраиваются под баланс или предыдущие выигрыши.",
    "rulesMaxWinTitle": "Поле и секретные комнаты",
    "rulesMaxWinText": "Таблица показывает обычные значения, без усилений. X10 BOOST умножает значения на 10; EX MULTI временно усиливает выбранные ячейки ещё в 10 раз. Множитель отдельной ячейки не является пределом суммарной выплаты всей бонусной цепочки.",
    "rulesVolatilityTitle": "Очереди бонусов",
    "rulesVolatilityText": "Новые ставки блокируются с начала подбора бонуса. Игра ждёт остановки уже запущенных шаров. Несколько бонусов идут по очереди: зелёный → жёлтый → красный → фиолетовый. Цифра над лузой — число ожидающих шаров, без текущего. В одной непрерывной очереди символ летит в счётчик только один раз.",
    "rulesDisclosureTitle": "Тестовая версия",
    "rulesDisclosureText": "Это локальный MVP с демонстрационным балансом, не игра на реальные деньги. Исход выбирается по фиксированным вероятностям; затем показывается существующая физически рассчитанная траектория. Анимация и скорость не меняют выплату. Таблицы других игроков помечены как демо."
  },
  "es": {
    "balance": "Saldo",
    "changeAvatar": "Cambiar avatar",
    "sound": "Efectos",
    "music": "Música",
    "animations": "Animaciones",
    "language": "Idioma",
    "gameRules": "Reglas del juego",
    "rules": "Reglas",
    "topUpTitle": "Recargar saldo",
    "topUpText": "Añade cualquier importe para seguir jugando.",
    "amount": "Importe",
    "topUp": "RECARGAR",
    "cancel": "CANCELAR",
    "totalHistory": "HISTORIAL:",
    "roundHistory": "Historial de rondas",
    "todayTopWins": "TOP DE HOY",
    "riskLevel": "RIESGO",
    "lines": "LÍNEAS",
    "low": "Bajo",
    "normal": "Normal",
    "high": "Alto",
    "pucks": "BOLAS",
    "auto": "AUTO",
    "bet": "APOSTAR",
    "wait": "ESPERA",
    "round": "RONDA",
    "livePlayers": "JUGADORES DEL PROTOTIPO",
    "liveSubtitle": "SIMULACIÓN LOCAL · MISMA MATEMÁTICA",
    "player": "Jugador",
    "type": "Tipo",
    "riskLines": "Riesgo / Líneas",
    "result": "Resultado",
    "payout": "Premio",
    "status": "Estado",
    "lost": "Perdió",
    "win": "Premio",
    "avatar": "Avatar",
    "showFullWinners": "Mostrar los 10 mejores premios de hoy",
    "showTopWinner": "Mostrar solo el mejor premio de hoy",
    "settings": "Ajustes",
    "volume": "Volumen",
    "audioSection": "Audio",
    "playSection": "Juego",
    "profileSection": "Perfil",
    "moreSection": "Más",
    "quickPlay": "Juego rápido · ×3",
    "quickHint": "Bolas más rápidas. Un lanzamiento cada 0,5 s en lugar de 1 s; los bonos mantienen su preparación.",
    "openHistory": "Mis lanzamientos",
    "openTop": "Top diario y premios de demo",
    "changeNickname": "Cambiar apodo",
    "yourNickname": "Tu apodo",
    "nicknameHint": "De 1 a 20 caracteres. Tu apodo aparece en el top diario.",
    "nicknameRequired": "Introduce un apodo",
    "save": "Guardar",
    "done": "Listo",
    "betPerBall": "Apuesta por bola · USD",
    "totalBet": "Apuesta total",
    "launchBall": "Lanzar una bola",
    "controls": "Controles del juego",
    "autoCount": "Número de lanzamientos pagados",
    "autoHint": "Pulsa Auto otra vez para detener nuevos lanzamientos. Las bolas en juego terminarán.",
    "startAuto": "Iniciar juego automático",
    "noHistory": "Aún no hay lanzamientos terminados",
    "close": "Cerrar",
    "time": "Hora",
    "profit": "Resultado neto",
    "demoWins": "Premios · DEMO",
    "backToGame": "Volver al juego",
    "collapse": "Contraer",
    "expand": "Expandir",
    "bonusHelpLabel": "Cómo funciona este bono",
    "bonusDemo": "Demostración del bono",
    "demoNote": "Solo ilustración · no es un resultado de juego",
    "pauseDemo": "Pausar animación",
    "playDemo": "Reproducir animación",
    "stepCapture": "Captura",
    "stepPrepare": "Preparación",
    "stepRelease": "Lanzamiento",
    "colorsTitle": "Colores de multiplicadores",
    "greenLabel": "Verde · hasta 1x",
    "yellowLabel": "Amarillo · más de 1x y menos de 10x",
    "redLabel": "Rojo · desde 10x",
    "purpleLabel": "Morado · X10 BOOST",
    "multiplierTable": "Multiplicadores actuales",
    "mainField": "Campo principal",
    "leftRoom": "Sala izquierda",
    "rightRoom": "Sala derecha",
    "loading": "Cargando Balloro X",
    "fieldLabel": "Campo de juego de Balloro X",
    "ruleLaunchTitle": "Una apuesta — una bola",
    "ruleLaunchText": "Elige la apuesta y 5, 7 o 9 líneas. Pulsa Spin para lanzar una bola. Mantén el botón para lanzar cada segundo; cada 0,5 segundos en juego rápido.",
    "ruleWinsTitle": "Parar en un multiplicador",
    "ruleWinsText": "El premio es la apuesta original × el multiplicador de la casilla final. Un retorno inferior a la apuesta no es una ganancia neta. Los resultados rojos y morados tienen música y paredes parpadeantes.",
    "rulePocketTitle": "X3 BALLS · tronera verde",
    "rulePocketFieldText": "La bola entra en la tronera verde de la izquierda. El cactus sube y vuela al contador. Basta un símbolo: tras la preparación salen tres bolas blancas. Sus premios se suman.",
    "ruleBoostTitle": "X10 BOOST · tronera morada",
    "ruleBoostText": "La tronera superior recoge un diamante. Cuando llega al contador y las otras bolas paran, el campo y ambas salas se vuelven morados. La bola sale; sus premios y los de sus bolas descendientes se multiplican por 10 hasta terminar toda la cadena.",
    "ruleMultiTitle": "EX MULTI · tronera amarilla",
    "ruleMultiText": "La tronera derecha recoge una estrella. Cuando llega al contador y las otras bolas paran, las luces eligen casillas y multiplican temporalmente sus valores por 10. La bola sale; debe parar en una casilla mejorada para recibir el premio aumentado.",
    "ruleLuckyTitle": "LUCKY SHOT · tronera roja",
    "ruleLuckyText": "La tronera inferior recoge una llama. La bola parpadea en la tronera mientras se prepara; después cae y aparece entre las dos salas secretas sin parpadear. Las salas parpadean, se elige una y la bola sale hacia ella. Todas sus casillas pagan; X10 BOOST también se aplica.",
    "ruleFieldTitle": "5, 7 o 9 líneas",
    "ruleFieldText": "Las líneas cambian las casillas y los multiplicadores, no la apuesta por bola. Consulta la tabla. La configuración solo cambia al terminar el juego activo.",
    "ruleAutoTitle": "Juego automático",
    "ruleAutoText": "Elige los lanzamientos pagados e inicia Auto. Se lanzan bolas cada 1 s, o cada 0,5 s en juego rápido. Los bonos pausan las nuevas apuestas. Los lanzamientos de bono no cobran otra apuesta.",
    "rulesAboutTitle": "Información útil",
    "rulesAboutIntro": "Los valores indican el premio como múltiplo de la apuesta original. El color identifica el nivel del multiplicador, sin cambiar el premio.",
    "rulesHowToWinTitle": "Premios y colores",
    "rulesHowToWinText": "Verde: hasta 1x. Amarillo: más de 1x y menos de 10x. Rojo: 10x o más. Morado: X10 BOOST activo. Solo los resultados rojos y morados activan la gran celebración. Todos los premios descendientes pertenecen a la apuesta original.",
    "rulesRtpTitle": "RTP teórico",
    "rulesRtpText": "El RTP teórico del MVP es 97,45% con 5, 7 y 9 líneas, incluyendo cadenas de bonos. Es una media de muchas apuestas, no una promesa por sesión. Las probabilidades no se adaptan al saldo ni a premios anteriores.",
    "rulesMaxWinTitle": "Campo y salas secretas",
    "rulesMaxWinText": "La tabla muestra valores normales. X10 BOOST los multiplica por 10; EX MULTI mejora ciertas casillas por otros 10. Un multiplicador de casilla no limita el premio total de una cadena.",
    "rulesVolatilityTitle": "Colas de bonos",
    "rulesVolatilityText": "Las apuestas se bloquean al empezar la recogida. Las bolas lanzadas terminan. Orden: verde → amarillo → rojo → morado. El número sobre una tronera cuenta las bolas en espera, sin la actual. Una cola continua envía su símbolo al contador solo una vez.",
    "rulesDisclosureTitle": "Versión de prueba",
    "rulesDisclosureText": "MVP local con saldo de demo, sin dinero real. Los resultados usan probabilidades fijas y trayectorias físicas precalculadas. La animación y la velocidad no cambian premios. Las tablas de otros jugadores son de demo."
  },
  "pt": {
    "balance": "Saldo",
    "changeAvatar": "Trocar avatar",
    "sound": "Efeitos",
    "music": "Música",
    "animations": "Animações",
    "language": "Idioma",
    "gameRules": "Regras do jogo",
    "rules": "Regras",
    "topUpTitle": "Adicionar saldo",
    "topUpText": "Adicione qualquer valor para continuar jogando.",
    "amount": "Valor",
    "topUp": "ADICIONAR",
    "cancel": "CANCELAR",
    "totalHistory": "HISTÓRICO:",
    "roundHistory": "Histórico de rodadas",
    "todayTopWins": "TOP DE HOJE",
    "riskLevel": "RISCO",
    "lines": "LINHAS",
    "low": "Baixo",
    "normal": "Normal",
    "high": "Alto",
    "pucks": "BOLAS",
    "auto": "AUTO",
    "bet": "APOSTAR",
    "wait": "AGUARDE",
    "round": "RODADA",
    "livePlayers": "JOGADORES DO PROTÓTIPO",
    "liveSubtitle": "SIMULAÇÃO LOCAL · MESMA MATEMÁTICA",
    "player": "Jogador",
    "type": "Tipo",
    "riskLines": "Risco / Linhas",
    "result": "Resultado",
    "payout": "Prêmio",
    "status": "Status",
    "lost": "Perdeu",
    "win": "Ganho",
    "avatar": "Avatar",
    "showFullWinners": "Mostrar os 10 maiores ganhos de hoje",
    "showTopWinner": "Mostrar apenas o maior ganho de hoje",
    "settings": "Configurações",
    "volume": "Volume",
    "audioSection": "Áudio",
    "playSection": "Jogo",
    "profileSection": "Perfil",
    "moreSection": "Mais",
    "quickPlay": "Jogo rápido · ×3",
    "quickHint": "Bolas mais rápidas. Um lançamento a cada 0,5 s em vez de 1 s; a preparação dos bônus mantém o ritmo.",
    "openHistory": "Meus lançamentos",
    "openTop": "Top diário e prêmios de demo",
    "changeNickname": "Alterar apelido",
    "yourNickname": "Seu apelido",
    "nicknameHint": "De 1 a 20 caracteres. Seu apelido aparece no top diário.",
    "nicknameRequired": "Digite um apelido",
    "save": "Salvar",
    "done": "Pronto",
    "betPerBall": "Aposta por bola · USD",
    "totalBet": "Aposta total",
    "launchBall": "Lançar uma bola",
    "controls": "Controles do jogo",
    "autoCount": "Número de lançamentos pagos",
    "autoHint": "Toque em Auto novamente para parar novos lançamentos. As bolas em jogo terminarão.",
    "startAuto": "Iniciar jogo automático",
    "noHistory": "Ainda não há lançamentos concluídos",
    "close": "Fechar",
    "time": "Hora",
    "profit": "Resultado líquido",
    "demoWins": "Prêmios · DEMO",
    "backToGame": "Voltar ao jogo",
    "collapse": "Recolher",
    "expand": "Expandir",
    "bonusHelpLabel": "Como funciona este bônus",
    "bonusDemo": "Demonstração do bônus",
    "demoNote": "Apenas ilustração · não é um resultado de jogo",
    "pauseDemo": "Pausar animação",
    "playDemo": "Reproduzir animação",
    "stepCapture": "Captura",
    "stepPrepare": "Preparação",
    "stepRelease": "Lançamento",
    "colorsTitle": "Cores dos multiplicadores",
    "greenLabel": "Verde · até 1x",
    "yellowLabel": "Amarelo · acima de 1x e abaixo de 10x",
    "redLabel": "Vermelho · a partir de 10x",
    "purpleLabel": "Roxo · X10 BOOST",
    "multiplierTable": "Multiplicadores atuais",
    "mainField": "Campo principal",
    "leftRoom": "Sala esquerda",
    "rightRoom": "Sala direita",
    "loading": "Carregando Balloro X",
    "fieldLabel": "Campo de jogo de Balloro X",
    "ruleLaunchTitle": "Uma aposta — uma bola",
    "ruleLaunchText": "Escolha a aposta e 5, 7 ou 9 linhas. Toque em Spin para lançar uma bola. Segure para novos lançamentos a cada segundo; a cada 0,5 segundo no jogo rápido.",
    "ruleWinsTitle": "Parar em um multiplicador",
    "ruleWinsText": "O prêmio é a aposta original × o multiplicador da célula final. Um retorno abaixo da aposta não é lucro líquido. Resultados vermelhos e roxos têm música e paredes piscando.",
    "rulePocketTitle": "X3 BALLS · buraco verde",
    "rulePocketFieldText": "A bola entra no buraco verde à esquerda. O cacto sobe e voa ao contador. Basta um símbolo: após a preparação saem três bolas brancas. Seus prêmios são somados.",
    "ruleBoostTitle": "X10 BOOST · buraco roxo",
    "ruleBoostText": "O buraco superior coleta um diamante. Quando chega ao contador e as outras bolas param, o campo e ambas as salas ficam roxos. A bola sai; seus prêmios e os de suas bolas descendentes são multiplicados por 10 até terminar toda a cadeia.",
    "ruleMultiTitle": "EX MULTI · buraco amarelo",
    "ruleMultiText": "O buraco direito coleta uma estrela. Quando chega ao contador e as outras bolas param, as luzes escolhem células e multiplicam temporariamente seus valores por 10. A bola sai; precisa parar em uma célula melhorada para receber o prêmio maior.",
    "ruleLuckyTitle": "LUCKY SHOT · buraco vermelho",
    "ruleLuckyText": "O buraco inferior coleta uma chama. A bola pisca no buraco durante a preparação; depois cai e aparece entre as duas salas secretas sem piscar. As salas piscam, uma é escolhida e a bola é lançada nela. Todas as células pagam; X10 BOOST também se aplica.",
    "ruleFieldTitle": "5, 7 ou 9 linhas",
    "ruleFieldText": "As linhas mudam as células e multiplicadores, não a aposta por bola. Veja a tabela. A configuração só muda quando o jogo ativo terminar.",
    "ruleAutoTitle": "Jogo automático",
    "ruleAutoText": "Escolha os lançamentos pagos e inicie Auto. As bolas saem a cada 1 s, ou 0,5 s no jogo rápido. Os bônus pausam novas apostas. Lançamentos de bônus não cobram outra aposta.",
    "rulesAboutTitle": "Informações úteis",
    "rulesAboutIntro": "Os valores mostram o prêmio como múltiplo da aposta original. A cor identifica o nível do multiplicador, sem alterar o prêmio.",
    "rulesHowToWinTitle": "Prêmios e cores",
    "rulesHowToWinText": "Verde: até 1x. Amarelo: acima de 1x e abaixo de 10x. Vermelho: 10x ou mais. Roxo: X10 BOOST ativo. Apenas resultados vermelhos e roxos ativam a grande celebração. Todos os descendentes pertencem à aposta original.",
    "rulesRtpTitle": "RTP teórico",
    "rulesRtpText": "O RTP teórico do MVP é 97,45% com 5, 7 e 9 linhas, incluindo cadeias de bônus. É uma média de muitas apostas, não uma promessa por sessão. As probabilidades não se adaptam ao saldo ou a prêmios anteriores.",
    "rulesMaxWinTitle": "Campo e salas secretas",
    "rulesMaxWinText": "A tabela mostra valores normais. X10 BOOST multiplica por 10; EX MULTI melhora células selecionadas por outros 10. Um multiplicador de célula não limita o prêmio total de uma cadeia.",
    "rulesVolatilityTitle": "Filas de bônus",
    "rulesVolatilityText": "As apostas travam quando a coleta começa. As bolas lançadas terminam. Ordem: verde → amarelo → vermelho → roxo. O número acima do buraco conta bolas aguardando, sem a atual. Uma fila contínua envia o símbolo ao contador uma única vez.",
    "rulesDisclosureTitle": "Versão de teste",
    "rulesDisclosureText": "MVP local com saldo de demo, sem dinheiro real. Os resultados usam probabilidades fixas e trajetórias físicas pré-calculadas. Animação e velocidade não mudam prêmios. As tabelas de outros jogadores são de demo."
  },
  "de": {
    "balance": "Guthaben",
    "changeAvatar": "Avatar ändern",
    "sound": "Soundeffekte",
    "music": "Musik",
    "animations": "Animationen",
    "language": "Sprache",
    "gameRules": "Spielregeln",
    "rules": "Regeln",
    "topUpTitle": "Guthaben aufladen",
    "topUpText": "Füge einen beliebigen Betrag hinzu, um weiterzuspielen.",
    "amount": "Betrag",
    "topUp": "AUFLADEN",
    "cancel": "ABBRECHEN",
    "totalHistory": "VERLAUF:",
    "roundHistory": "Rundenverlauf",
    "todayTopWins": "TOP HEUTE",
    "riskLevel": "RISIKO",
    "lines": "LINIEN",
    "low": "Niedrig",
    "normal": "Normal",
    "high": "Hoch",
    "pucks": "BÄLLE",
    "auto": "AUTO",
    "bet": "SETZEN",
    "wait": "WARTEN",
    "round": "RUNDE",
    "livePlayers": "LIVE-PROTOTYP-SPIELER",
    "liveSubtitle": "LOKALE SIMULATION · GEMEINSAME MATHEMATIK",
    "player": "Spieler",
    "type": "Typ",
    "riskLines": "Risiko / Linien",
    "result": "Ergebnis",
    "payout": "Auszahlung",
    "status": "Status",
    "lost": "Verloren",
    "win": "Gewinn",
    "avatar": "Avatar",
    "showFullWinners": "Heutige Top 10 anzeigen",
    "showTopWinner": "Nur heutigen Top-Gewinn anzeigen",
    "settings": "Einstellungen",
    "volume": "Lautstärke",
    "audioSection": "Audio",
    "playSection": "Spiel",
    "profileSection": "Profil",
    "moreSection": "Mehr",
    "quickPlay": "Schnellspiel · ×3",
    "quickHint": "Schnellere Bälle. Ein Start alle 0,5 s statt 1 s; die Bonusvorbereitung bleibt gleich.",
    "openHistory": "Meine Würfe",
    "openTop": "Tagestop und Demo-Gewinne",
    "changeNickname": "Spitznamen ändern",
    "yourNickname": "Dein Spitzname",
    "nicknameHint": "1–20 Zeichen. Dein Spitzname erscheint im Tagestop.",
    "nicknameRequired": "Spitznamen eingeben",
    "save": "Speichern",
    "done": "Fertig",
    "betPerBall": "Einsatz pro Ball · USD",
    "totalBet": "Gesamteinsatz",
    "launchBall": "Einen Ball starten",
    "controls": "Spielsteuerung",
    "autoCount": "Anzahl bezahlter Würfe",
    "autoHint": "Autoplay erneut antippen, um neue Starts zu stoppen. Aktive Bälle spielen zu Ende.",
    "startAuto": "Autoplay starten",
    "noHistory": "Noch keine abgeschlossenen Würfe",
    "close": "Schließen",
    "time": "Zeit",
    "profit": "Nettoergebnis",
    "demoWins": "Gewinne · DEMO",
    "backToGame": "Zurück zum Spiel",
    "collapse": "Einklappen",
    "expand": "Ausklappen",
    "bonusHelpLabel": "So funktioniert dieser Bonus",
    "bonusDemo": "Bonusdemonstration",
    "demoNote": "Nur Illustration · kein Spielergebnis",
    "pauseDemo": "Animation pausieren",
    "playDemo": "Animation abspielen",
    "stepCapture": "Aufnahme",
    "stepPrepare": "Vorbereitung",
    "stepRelease": "Start",
    "colorsTitle": "Multiplikatorfarben",
    "greenLabel": "Grün · bis 1x",
    "yellowLabel": "Gelb · über 1x, unter 10x",
    "redLabel": "Rot · ab 10x",
    "purpleLabel": "Violett · X10 BOOST",
    "multiplierTable": "Aktuelle Multiplikatoren",
    "mainField": "Hauptfeld",
    "leftRoom": "Linker Raum",
    "rightRoom": "Rechter Raum",
    "loading": "Balloro X wird geladen",
    "fieldLabel": "Balloro-X-Spielfeld",
    "ruleLaunchTitle": "Ein Einsatz — ein Ball",
    "ruleLaunchText": "Wähle Einsatz und 5, 7 oder 9 Linien. Tippe auf Spin für einen Ball. Halte die Taste für Starts jede Sekunde; im Schnellspiel alle 0,5 Sekunden.",
    "ruleWinsTitle": "Stopp auf einem Multiplikator",
    "ruleWinsText": "Die Auszahlung ist ursprünglicher Einsatz × Multiplikator der Endzelle. Eine Rückzahlung unter dem Einsatz ist kein Nettogewinn. Rote und violette Ergebnisse haben Gewinnmusik und blinkende Wände.",
    "rulePocketTitle": "X3 BALLS · grünes Loch",
    "rulePocketFieldText": "Der Ball wird in das grüne Loch links gezogen. Der Kaktus steigt auf und fliegt zum Zähler. Ein Symbol genügt: nach der Vorbereitung starten drei weiße Bälle. Ihre Auszahlungen werden addiert.",
    "ruleBoostTitle": "X10 BOOST · violettes Loch",
    "ruleBoostText": "Das obere Loch sammelt einen Diamanten. Nach seiner Ankunft am Zähler und dem Stopp der anderen Bälle werden Feld und beide Räume violett. Dann startet der Ball; seine Gewinne und die seiner Bonus-Nachfolger werden bis zum Ende der Kette mit 10 multipliziert.",
    "ruleMultiTitle": "EX MULTI · gelbes Loch",
    "ruleMultiText": "Das rechte Loch sammelt einen Stern. Nach seiner Ankunft und dem Stopp anderer Bälle wählen wandernde Lichter Zellen aus und multiplizieren ihre Werte vorübergehend mit 10. Der Ball startet; ein erhöhter Gewinn erfordert einen Stopp auf einer verstärkten Zelle.",
    "ruleLuckyTitle": "LUCKY SHOT · rotes Loch",
    "ruleLuckyText": "Das untere Loch sammelt eine Flamme. Während der Vorbereitung blinkt der Ball im Loch. Dann fällt er hinein und erscheint ohne Blinken zwischen zwei Geheimräumen. Die Räume blinken, einer wird gewählt und der Ball hineingeschossen. Alle Zellen zahlen; X10 BOOST gilt auch dort.",
    "ruleFieldTitle": "5, 7 oder 9 Linien",
    "ruleFieldText": "Linien ändern Zellen und Multiplikatoren, nicht den Einsatz pro Ball. Siehe Tabelle. Die Konfiguration ist erst nach Ende des aktiven Spiels änderbar.",
    "ruleAutoTitle": "Autoplay",
    "ruleAutoText": "Wähle bezahlte Würfe und starte Auto. Bälle starten jede 1 s, im Schnellspiel alle 0,5 s. Bonusvorbereitung und Bonusspiel pausieren neue Einsätze. Bonusstarts kosten keinen weiteren Einsatz.",
    "rulesAboutTitle": "Gut zu wissen",
    "rulesAboutIntro": "Feldwerte zeigen die Auszahlung als Vielfaches des ursprünglichen Einsatzes. Die Farbe bezeichnet die Multiplikatorstufe, ohne die Auszahlung zu verändern.",
    "rulesHowToWinTitle": "Auszahlungen und Farben",
    "rulesHowToWinText": "Grün: bis 1x. Gelb: über 1x, unter 10x. Rot: ab 10x. Violett: aktiver X10 BOOST. Nur rote und violette Ergebnisse lösen die große Gewinnfeier aus. Alle Bonus-Nachfolger gehören zum ursprünglichen Einsatz.",
    "rulesRtpTitle": "Theoretischer RTP",
    "rulesRtpText": "Der theoretische RTP dieses MVP beträgt 97,45% bei 5, 7 und 9 Linien einschließlich Bonusketten. Das ist ein Durchschnitt vieler Einsätze, keine Sitzungszusage. Wahrscheinlichkeiten reagieren nicht auf Guthaben oder frühere Gewinne.",
    "rulesMaxWinTitle": "Feld und Geheimräume",
    "rulesMaxWinText": "Die Tabelle zeigt normale Werte. X10 BOOST multipliziert mit 10; EX MULTI verstärkt gewählte Zellen um weitere 10. Ein Zellmultiplikator begrenzt nicht die Gesamtauszahlung einer Kette.",
    "rulesVolatilityTitle": "Bonuswarteschlangen",
    "rulesVolatilityText": "Neue Einsätze sperren ab Beginn der Sammlung. Gestartete Bälle rollen zu Ende. Reihenfolge: grün → gelb → rot → violett. Die Zahl über einem Loch zählt wartende Bälle ohne den aktuellen. Eine durchgehende Warteschlange sendet ihr Symbol nur einmal zum Zähler.",
    "rulesDisclosureTitle": "Testversion",
    "rulesDisclosureText": "Lokaler MVP mit Demo-Guthaben, kein Echtgeldspiel. Ergebnisse verwenden feste Wahrscheinlichkeiten und vorberechnete physikalische Flugbahnen. Animation und Geschwindigkeit ändern keine Auszahlung. Andere Spielertabellen sind als Demo gekennzeichnet."
  },
  "fr": {
    "balance": "Solde",
    "changeAvatar": "Changer d’avatar",
    "sound": "Effets sonores",
    "music": "Musique",
    "animations": "Animations",
    "language": "Langue",
    "gameRules": "Règles du jeu",
    "rules": "Règles",
    "topUpTitle": "Recharger le solde",
    "topUpText": "Ajoutez le montant de votre choix pour continuer.",
    "amount": "Montant",
    "topUp": "RECHARGER",
    "cancel": "ANNULER",
    "totalHistory": "HISTORIQUE :",
    "roundHistory": "Historique des manches",
    "todayTopWins": "TOP DU JOUR",
    "riskLevel": "RISQUE",
    "lines": "LIGNES",
    "low": "Faible",
    "normal": "Normal",
    "high": "Élevé",
    "pucks": "BOULES",
    "auto": "AUTO",
    "bet": "MISER",
    "wait": "ATTENDRE",
    "round": "MANCHE",
    "livePlayers": "JOUEURS DU PROTOTYPE",
    "liveSubtitle": "SIMULATION LOCALE · MÊMES MATHÉMATIQUES",
    "player": "Joueur",
    "type": "Type",
    "riskLines": "Risque / Lignes",
    "result": "Résultat",
    "payout": "Gain",
    "status": "Statut",
    "lost": "Perdu",
    "win": "Gain",
    "avatar": "Avatar",
    "showFullWinners": "Afficher les 10 meilleurs gains du jour",
    "showTopWinner": "Afficher uniquement le meilleur gain du jour",
    "settings": "Réglages",
    "volume": "Volume",
    "audioSection": "Audio",
    "playSection": "Jeu",
    "profileSection": "Profil",
    "moreSection": "Plus",
    "quickPlay": "Jeu rapide · ×3",
    "quickHint": "Boules plus rapides. Un lancer toutes les 0,5 s au lieu de 1 s ; les bonus gardent leur préparation.",
    "openHistory": "Mes lancers",
    "openTop": "Top du jour et gains de démo",
    "changeNickname": "Changer de pseudo",
    "yourNickname": "Votre pseudo",
    "nicknameHint": "De 1 à 20 caractères. Votre pseudo apparaît au top du jour.",
    "nicknameRequired": "Saisissez un pseudo",
    "save": "Enregistrer",
    "done": "Terminé",
    "betPerBall": "Mise par boule · USD",
    "totalBet": "Mise totale",
    "launchBall": "Lancer une boule",
    "controls": "Commandes du jeu",
    "autoCount": "Nombre de lancers payants",
    "autoHint": "Appuyez à nouveau sur Auto pour arrêter les nouveaux lancers. Les boules en jeu finiront.",
    "startAuto": "Démarrer le jeu automatique",
    "noHistory": "Aucun lancer terminé",
    "close": "Fermer",
    "time": "Heure",
    "profit": "Résultat net",
    "demoWins": "Gains · DÉMO",
    "backToGame": "Revenir au jeu",
    "collapse": "Réduire",
    "expand": "Développer",
    "bonusHelpLabel": "Fonctionnement du bonus",
    "bonusDemo": "Démonstration du bonus",
    "demoNote": "Illustration uniquement · pas un résultat de jeu",
    "pauseDemo": "Mettre en pause",
    "playDemo": "Lire l’animation",
    "stepCapture": "Collecte",
    "stepPrepare": "Préparation",
    "stepRelease": "Lancement",
    "colorsTitle": "Couleurs des multiplicateurs",
    "greenLabel": "Vert · jusqu’à 1x",
    "yellowLabel": "Jaune · plus de 1x, moins de 10x",
    "redLabel": "Rouge · à partir de 10x",
    "purpleLabel": "Violet · X10 BOOST",
    "multiplierTable": "Multiplicateurs actuels",
    "mainField": "Terrain principal",
    "leftRoom": "Salle gauche",
    "rightRoom": "Salle droite",
    "loading": "Chargement de Balloro X",
    "fieldLabel": "Terrain de jeu Balloro X",
    "ruleLaunchTitle": "Une mise — une boule",
    "ruleLaunchText": "Choisissez la mise et 5, 7 ou 9 lignes. Appuyez sur Spin pour lancer une boule. Maintenez pour un lancer chaque seconde ; toutes les 0,5 secondes en jeu rapide.",
    "ruleWinsTitle": "Arrêt sur un multiplicateur",
    "ruleWinsText": "Le gain est la mise initiale × le multiplicateur de la case finale. Un retour inférieur à la mise n’est pas un bénéfice net. Les résultats rouges et violets ont une musique et des murs clignotants.",
    "rulePocketTitle": "X3 BALLS · poche verte",
    "rulePocketFieldText": "La boule entre dans la poche verte à gauche. Le cactus monte et vole au compteur. Un symbole suffit : après la préparation, trois boules blanches sont lancées. Leurs gains s’additionnent.",
    "ruleBoostTitle": "X10 BOOST · poche violette",
    "ruleBoostText": "La poche supérieure collecte un diamant. À son arrivée au compteur et après l’arrêt des autres boules, le terrain et les deux salles deviennent violets. La boule est lancée ; ses gains et ceux de ses descendants bonus sont multipliés par 10 jusqu’à la fin de la chaîne.",
    "ruleMultiTitle": "EX MULTI · poche jaune",
    "ruleMultiText": "La poche droite collecte une étoile. À son arrivée et après l’arrêt des autres boules, les lumières choisissent des cases et multiplient temporairement leurs valeurs par 10. La boule part ; elle doit s’arrêter sur une case améliorée pour obtenir le gain augmenté.",
    "ruleLuckyTitle": "LUCKY SHOT · poche rouge",
    "ruleLuckyText": "La poche inférieure collecte une flamme. La boule clignote dans la poche pendant la préparation, puis tombe et apparaît entre les deux salles secrètes sans clignoter. Les salles clignotent, l’une est choisie et la boule y est lancée. Toutes les cases paient ; X10 BOOST s’y applique aussi.",
    "ruleFieldTitle": "5, 7 ou 9 lignes",
    "ruleFieldText": "Les lignes changent les cases et multiplicateurs, pas la mise par boule. Consultez le tableau. La configuration ne change qu’après la fin du jeu actif.",
    "ruleAutoTitle": "Jeu automatique",
    "ruleAutoText": "Choisissez les lancers payants et démarrez Auto. Les boules partent toutes les 1 s, ou 0,5 s en jeu rapide. Les bonus suspendent les nouvelles mises. Les lancers bonus ne coûtent pas de nouvelle mise.",
    "rulesAboutTitle": "À savoir",
    "rulesAboutIntro": "Les valeurs indiquent le gain comme multiple de la mise initiale. La couleur identifie le niveau du multiplicateur sans modifier le gain.",
    "rulesHowToWinTitle": "Gains et couleurs",
    "rulesHowToWinText": "Vert : jusqu’à 1x. Jaune : plus de 1x, moins de 10x. Rouge : 10x ou plus. Violet : X10 BOOST actif. Seuls les résultats rouges et violets déclenchent la grande célébration. Tous les descendants bonus appartiennent à la mise initiale.",
    "rulesRtpTitle": "RTP théorique",
    "rulesRtpText": "Le RTP théorique du MVP est de 97,45% avec 5, 7 et 9 lignes, chaînes bonus incluses. C’est une moyenne de nombreuses mises, pas une promesse par session. Les probabilités ne s’adaptent pas au solde ou aux gains précédents.",
    "rulesMaxWinTitle": "Terrain et salles secrètes",
    "rulesMaxWinText": "Le tableau montre les valeurs normales. X10 BOOST multiplie par 10 ; EX MULTI améliore certaines cases par 10 de plus. Un multiplicateur de case n’est pas une limite au gain total d’une chaîne.",
    "rulesVolatilityTitle": "Files de bonus",
    "rulesVolatilityText": "Les nouvelles mises sont bloquées dès la collecte. Les boules déjà lancées finissent. Ordre : vert → jaune → rouge → violet. Le nombre au-dessus d’une poche compte les boules en attente, sans l’actuelle. Une file continue envoie son symbole au compteur une seule fois.",
    "rulesDisclosureTitle": "Version de test",
    "rulesDisclosureText": "MVP local avec un solde de démo, sans argent réel. Les résultats utilisent des probabilités fixes et des trajectoires physiques précalculées. L’animation et la vitesse ne changent pas les gains. Les tableaux des autres joueurs sont indiqués comme démo."
  }
};
