/* Player-facing rules and labels in all six languages. */
window.BalloroPlayerCopy = {
  "en": {
    "balance": "Balance",
    "changeAvatar": "Avatar",
    "sound": "Sounds",
    "music": "Music",
    "animations": "Animations",
    "language": "Language",
    "gameRules": "Rules",
    "rules": "Rules",
    "topUpTitle": "Top Up Balance",
    "topUpText": "Add any amount to continue playing.",
    "amount": "Amount",
    "topUp": "TOP UP",
    "cancel": "CANCEL",
    "totalHistory": "HISTORY:",
    "roundHistory": "Round History",
    "todayTopWins": "TODAY TOP WINS",
    "riskLevel": "RISK",
    "lines": "LINES",
    "low": "Low",
    "normal": "Normal",
    "high": "High",
    "pucks": "BALLS",
    "auto": "AUTO",
    "bet": "BET",
    "wait": "WAIT",
    "round": "ROUND",
    "livePlayers": "LIVE PROTOTYPE PLAYERS",
    "liveSubtitle": "LOCAL SIMULATION · SHARED GAME MATH",
    "player": "Player",
    "type": "Type",
    "riskLines": "Risk / Lines",
    "result": "Result",
    "payout": "Payout",
    "status": "Status",
    "lost": "Lost",
    "win": "Win",
    "avatar": "Avatar",
    "showFullWinners": "Show full today top wins",
    "showTopWinner": "Show only today's top win",
    "settings": "Settings",
    "volume": "Volume",
    "audioSection": "Audio",
    "playSection": "Play",
    "profileSection": "Profile & language",
    "moreSection": "More",
    "quickPlay": "Quick Play",
    "quickHint": "Faster balls and more frequent repeat bets.",
    "openHistory": "My shots",
    "openTop": "Daily top",
    "changeNickname": "Nickname",
    "yourNickname": "Your nickname",
    "nicknameHint": "1–20 characters. Shown in the daily top.",
    "nicknameRequired": "Enter a nickname",
    "save": "Save",
    "done": "Done",
    "betPerBall": "Stake per ball · USD",
    "totalBet": "Total stake",
    "launchBall": "Launch one ball",
    "controls": "Game controls",
    "autoCount": "Paid shots",
    "autoHint": "The ■ button stops new bets. Balls in play finish.",
    "startAuto": "Start autoplay",
    "noHistory": "No completed shots yet",
    "close": "Close",
    "time": "Time",
    "profit": "Net result",
    "demoWins": "Wins · DEMO",
    "backToGame": "Back to game",
    "collapse": "Collapse",
    "expand": "Expand",
    "bonusHelpLabel": "How this bonus works",
    "bonusDemo": "See example",
    "demoNote": "Example, not a promised win",
    "pauseDemo": "Pause",
    "playDemo": "Replay",
    "stepCapture": "Pocket hit",
    "stepPrepare": "Bonus",
    "stepRelease": "Payout",
    "colorsTitle": "Multiplier colours",
    "greenLabel": "Green · up to 1x",
    "yellowLabel": "Yellow · above 1x, below 10x",
    "redLabel": "Red · 10x or more",
    "purpleLabel": "Purple · 10X BOOST",
    "multiplierTable": "Current multipliers",
    "mainField": "Main field",
    "leftRoom": "Left bonus field",
    "rightRoom": "Right bonus field",
    "loading": "Loading Balloro X",
    "fieldLabel": "Balloro X game field",
    "ruleLaunchTitle": "Launch the balls",
    "ruleLaunchText": "Choose a stake per ball, 1–3 balls and 5, 7 or 9 lines. Press SPIN. Holding it repeats bets.",
    "ruleWinsTitle": "Stop on a multiplier",
    "ruleWinsText": "Stake per ball × its stopping cell multiplier. All ball payouts add up. Less than the stake is a partial return, not profit.",
    "rulePocketTitle": "3X BALLS · green pocket",
    "rulePocketFieldText": "Three balls replace one. Their payouts add up. No extra stake.",
    "ruleBoostTitle": "10X BOOST · purple pocket",
    "ruleBoostText": "Main and bonus field multipliers become ×10 for this ball and the balls it creates. Another purple hit extends the effect; it does not multiply it again.",
    "ruleMultiTitle": "EX MULTI · yellow pocket",
    "ruleMultiText": "Selected main-field cells get ×10. The ball launches again: it must stop in an enhanced cell for the higher payout.",
    "ruleLuckyTitle": "LUCKY SHOT · red pocket",
    "ruleLuckyText": "The ball sinks, then launches into one of two Bonus fields. Every cell pays. 10X BOOST also applies here.",
    "ruleFieldTitle": "5, 7 or 9 lines",
    "ruleFieldText": "Lines change the field and multipliers, not the stake per ball. Change them between games.",
    "ruleAutoTitle": "Autoplay",
    "ruleAutoText": "Choose a shot count and optional stop conditions. Bonuses cost no extra stake. Hiding the game pauses it; returning resumes it. After resizing, tap the screen.",
    "rulesAboutTitle": "Good to know",
    "rulesAboutIntro": "Multipliers shown without bonuses.",
    "rulesHowToWinTitle": "Big wins",
    "rulesHowToWinText": "10x or more plays music and flashing, including purple wins. Boosted green cells turn yellow from 1x and red from 10x. Purple means 10X BOOST.",
    "rulesRtpTitle": "Theoretical RTP",
    "rulesRtpText": "RTP is 97.45% on all lines, including bonuses. This is an average over many bets, not a guarantee for one game.",
    "rulesMaxWinTitle": "Maximum win",
    "rulesMaxWinText": "Maximum per paid ball: 5 lines — 1,200x with 10X BOOST, then LUCKY SHOT and 120x on the right Bonus field. On 7 / 9 lines: 6,000x / 8,500x with EX MULTI and 10X BOOST, in either order, then a hit on the boosted centre. Each ball can enter at most two pockets in total. Created balls inherit the entries already used.",
    "rulesVolatilityTitle": "Bonuses and new bets",
    "rulesVolatilityText": "Bonuses play in turn; new bets wait for them. Purple and yellow boosts can combine. Yellow only boosts the main field.",
    "rulesDisclosureTitle": "Demo game",
    "rulesDisclosureText": "The balance and player tables are for demonstration. Outcomes are random and do not depend on balance or previous wins. Speed does not change payouts.",
    "rulesTab0": "How to play",
    "rulesTab1": "Bonuses",
    "rulesTab2": "Payouts",
    "rulesBonusIntro": "Land in a pocket to trigger a bonus without a new stake."
  },
  "ru": {
    "balance": "Баланс",
    "changeAvatar": "Аватар",
    "sound": "Звуки",
    "music": "Музыка",
    "animations": "Анимации",
    "language": "Язык",
    "gameRules": "Правила",
    "rules": "Правила",
    "topUpTitle": "Пополнить баланс",
    "topUpText": "Добавьте любую сумму, чтобы продолжить игру.",
    "amount": "Сумма",
    "topUp": "ПОПОЛНИТЬ",
    "cancel": "ОТМЕНА",
    "totalHistory": "ИСТОРИЯ:",
    "roundHistory": "История раундов",
    "todayTopWins": "ТОП ДНЯ",
    "riskLevel": "РИСК",
    "lines": "ЛИНИИ",
    "low": "Низкий",
    "normal": "Средний",
    "high": "Высокий",
    "pucks": "ШАРЫ",
    "auto": "АВТО",
    "bet": "СТАВКА",
    "wait": "ЖДАТЬ",
    "round": "РАУНД",
    "livePlayers": "ИГРОКИ ПРОТОТИПА",
    "liveSubtitle": "ЛОКАЛЬНАЯ СИМУЛЯЦИЯ · ОБЩАЯ МАТЕМАТИКА",
    "player": "Игрок",
    "type": "Тип",
    "riskLines": "Риск / Линии",
    "result": "Результат",
    "payout": "Выплата",
    "status": "Статус",
    "lost": "Проигрыш",
    "win": "Выигрыш",
    "avatar": "Аватар",
    "showFullWinners": "Показать 10 лучших выигрышей сегодня",
    "showTopWinner": "Показать только лучший выигрыш сегодня",
    "settings": "Настройки",
    "volume": "Громкость",
    "audioSection": "Звук",
    "playSection": "Игра",
    "profileSection": "Профиль и язык",
    "moreSection": "Дополнительно",
    "quickPlay": "Быстрая игра",
    "quickHint": "Шары движутся быстрее, ставки повторяются чаще.",
    "openHistory": "Мои броски",
    "openTop": "Топ дня",
    "changeNickname": "Ник",
    "yourNickname": "Ваш ник",
    "nicknameHint": "1–20 символов. Видно в топе дня.",
    "nicknameRequired": "Введите ник",
    "save": "Сохранить",
    "done": "Готово",
    "betPerBall": "Ставка на шар · USD",
    "totalBet": "Общая ставка",
    "launchBall": "Запустить один шар",
    "controls": "Управление игрой",
    "autoCount": "Платные броски",
    "autoHint": "Кнопка ■ останавливает новые ставки. Шары на поле завершают игру.",
    "startAuto": "Начать автоигру",
    "noHistory": "Завершённых бросков пока нет",
    "close": "Закрыть",
    "time": "Время",
    "profit": "Чистый результат",
    "demoWins": "Выигрыши · ДЕМО",
    "backToGame": "Вернуться к игре",
    "collapse": "Свернуть",
    "expand": "Развернуть",
    "bonusHelpLabel": "Как работает этот бонус",
    "bonusDemo": "Посмотреть пример",
    "demoNote": "Пример, не обещание выигрыша",
    "pauseDemo": "Пауза",
    "playDemo": "Повторить",
    "stepCapture": "Попадание",
    "stepPrepare": "Бонус",
    "stepRelease": "Выигрыш",
    "colorsTitle": "Цвета множителей",
    "greenLabel": "Зелёный · до 1x",
    "yellowLabel": "Жёлтый · больше 1x, меньше 10x",
    "redLabel": "Красный · от 10x",
    "purpleLabel": "Фиолетовый · 10X BOOST",
    "multiplierTable": "Текущие множители",
    "mainField": "Основное поле",
    "leftRoom": "Левое бонусное поле",
    "rightRoom": "Правое бонусное поле",
    "loading": "Загрузка Balloro X",
    "fieldLabel": "Игровое поле Balloro X",
    "ruleLaunchTitle": "Запустите шары",
    "ruleLaunchText": "Выберите ставку на шар, 1–3 шара и 5, 7 или 9 линий. Нажмите СПИН. Удержание кнопки повторяет ставки.",
    "ruleWinsTitle": "Шар остановился — выплата",
    "ruleWinsText": "Ставка на шар × множитель его ячейки. Выплаты всех шаров складываются. Меньше ставки — частичный возврат, не прибыль.",
    "rulePocketTitle": "3X BALLS · зелёная луза",
    "rulePocketFieldText": "Вместо одного шара вылетают три. Их выплаты складываются. Дополнительная ставка не нужна.",
    "ruleBoostTitle": "10X BOOST · фиолетовая луза",
    "ruleBoostText": "Множители становятся ×10 на основном и бонусных полях. Бонус действует на этот шар и полученные от него шары. Повторное попадание продлевает эффект, но не умножает его снова.",
    "ruleMultiTitle": "EX MULTI · жёлтая луза",
    "ruleMultiText": "Выбранные ячейки основного поля получают ×10. Шар вылетает снова: для повышенной выплаты он должен остановиться в усиленной ячейке.",
    "ruleLuckyTitle": "LUCKY SHOT · красная луза",
    "ruleLuckyText": "Шар проваливается в лузу, затем запускается на одном из двух Бонусных полей. Все их ячейки платят. 10X BOOST действует и здесь.",
    "ruleFieldTitle": "5, 7 или 9 линий",
    "ruleFieldText": "Линии меняют поле и множители. Ставка на шар не меняется. Выбор доступен между играми.",
    "ruleAutoTitle": "Автоигра",
    "ruleAutoText": "Выберите число бросков и при желании условия остановки. Бонусы не требуют новой ставки. При сворачивании игра на паузе; при возвращении продолжается. После изменения размера окна коснитесь экрана.",
    "rulesAboutTitle": "Важно знать",
    "rulesAboutIntro": "Все множители указаны без бонусов.",
    "rulesHowToWinTitle": "Крупный выигрыш",
    "rulesHowToWinText": "От 10x — музыка и мигание, в том числе на фиолетовом поле. Усиленные зелёные ячейки от 1x становятся жёлтыми, от 10x — красными. Фиолетовый цвет означает 10X BOOST.",
    "rulesRtpTitle": "Теоретический RTP",
    "rulesRtpText": "RTP — 97,45% на всех линиях, включая бонусы. Это средний возврат на множестве ставок, не гарантия результата одной игры.",
    "rulesMaxWinTitle": "Максимальный выигрыш",
    "rulesMaxWinText": "Максимум на один оплаченный шар: 5 линий — 1 200x. Для этого нужны 10X BOOST, затем LUCKY SHOT и попадание на 120x правого Бонусного поля. На 7 / 9 линиях — 6 000x / 8 500x: EX MULTI и 10X BOOST в любом порядке, затем попадание в усиленный центр. Шар может войти не более чем в две лузы всего. Полученные от него шары наследуют использованные входы.",
    "rulesVolatilityTitle": "Бонусы и новые ставки",
    "rulesVolatilityText": "Бонусы разыгрываются по очереди. Новые ставки ждут завершения бонуса. Усиления фиолетового и жёлтого бонусов могут сочетаться; жёлтый усиливает только основное поле.",
    "rulesDisclosureTitle": "Демо-игра",
    "rulesDisclosureText": "Баланс и таблицы игроков демонстрационные. Исход случаен и не зависит от баланса или прошлых выигрышей. Скорость игры не меняет выплату.",
    "rulesTab0": "Как играть",
    "rulesTab1": "Бонусы",
    "rulesTab2": "Выплаты",
    "rulesBonusIntro": "Попадание в лузу запускает бонус без новой ставки."
  },
  "es": {
    "balance": "Saldo",
    "changeAvatar": "Avatar",
    "sound": "Sonidos",
    "music": "Música",
    "animations": "Animaciones",
    "language": "Idioma",
    "gameRules": "Reglas",
    "rules": "Reglas",
    "topUpTitle": "Recargar saldo",
    "topUpText": "Añade cualquier importe para seguir jugando.",
    "amount": "Importe",
    "topUp": "RECARGAR",
    "cancel": "CANCELAR",
    "totalHistory": "HISTORIAL:",
    "roundHistory": "Historial de rondas",
    "todayTopWins": "TOP DE HOY",
    "riskLevel": "RIESGO",
    "lines": "LÍNEAS",
    "low": "Bajo",
    "normal": "Normal",
    "high": "Alto",
    "pucks": "BOLAS",
    "auto": "AUTO",
    "bet": "APOSTAR",
    "wait": "ESPERA",
    "round": "RONDA",
    "livePlayers": "JUGADORES DEL PROTOTIPO",
    "liveSubtitle": "SIMULACIÓN LOCAL · MISMA MATEMÁTICA",
    "player": "Jugador",
    "type": "Tipo",
    "riskLines": "Riesgo / Líneas",
    "result": "Resultado",
    "payout": "Premio",
    "status": "Estado",
    "lost": "Perdió",
    "win": "Premio",
    "avatar": "Avatar",
    "showFullWinners": "Mostrar los 10 mejores premios de hoy",
    "showTopWinner": "Mostrar solo el mejor premio de hoy",
    "settings": "Ajustes",
    "volume": "Volumen",
    "audioSection": "Audio",
    "playSection": "Juego",
    "profileSection": "Perfil e idioma",
    "moreSection": "Más",
    "quickPlay": "Juego rápido",
    "quickHint": "Bolas más rápidas y apuestas repetidas más frecuentes.",
    "openHistory": "Mis lanzamientos",
    "openTop": "Top de hoy",
    "changeNickname": "Apodo",
    "yourNickname": "Tu apodo",
    "nicknameHint": "1–20 caracteres. Visible en el top de hoy.",
    "nicknameRequired": "Introduce un apodo",
    "save": "Guardar",
    "done": "Listo",
    "betPerBall": "Apuesta por bola · USD",
    "totalBet": "Apuesta total",
    "launchBall": "Lanzar una bola",
    "controls": "Controles del juego",
    "autoCount": "Lanzamientos pagados",
    "autoHint": "El botón ■ detiene nuevas apuestas. Las bolas en juego terminan.",
    "startAuto": "Iniciar juego automático",
    "noHistory": "Aún no hay lanzamientos terminados",
    "close": "Cerrar",
    "time": "Hora",
    "profit": "Resultado neto",
    "demoWins": "Premios · DEMO",
    "backToGame": "Volver al juego",
    "collapse": "Contraer",
    "expand": "Expandir",
    "bonusHelpLabel": "Cómo funciona este bono",
    "bonusDemo": "Ver ejemplo",
    "demoNote": "Ejemplo, no premio garantizado",
    "pauseDemo": "Pausa",
    "playDemo": "Repetir",
    "stepCapture": "Entrada",
    "stepPrepare": "Bono",
    "stepRelease": "Premio",
    "colorsTitle": "Colores de multiplicadores",
    "greenLabel": "Verde · hasta 1x",
    "yellowLabel": "Amarillo · más de 1x y menos de 10x",
    "redLabel": "Rojo · desde 10x",
    "purpleLabel": "Morado · 10X BOOST",
    "multiplierTable": "Multiplicadores actuales",
    "mainField": "Campo principal",
    "leftRoom": "Campo bonus izquierdo",
    "rightRoom": "Campo bonus derecho",
    "loading": "Cargando Balloro X",
    "fieldLabel": "Campo de juego de Balloro X",
    "ruleLaunchTitle": "Lanza las bolas",
    "ruleLaunchText": "Elige apuesta por bola, 1–3 bolas y 5, 7 o 9 líneas. Pulsa SPIN. Mantenerlo pulsado repite apuestas.",
    "ruleWinsTitle": "Parada y premio",
    "ruleWinsText": "Apuesta por bola × multiplicador de su casilla final. Los premios se suman. Recibir menos de la apuesta es retorno parcial, no beneficio.",
    "rulePocketTitle": "3X BALLS · tronera verde",
    "rulePocketFieldText": "Tres bolas sustituyen a una. Sus premios se suman. Sin apuesta adicional.",
    "ruleBoostTitle": "10X BOOST · tronera morada",
    "ruleBoostText": "Los campos principal y bonus pasan a ×10 para esta bola y las que genera. Otra entrada morada prolonga el efecto, sin volver a multiplicarlo.",
    "ruleMultiTitle": "EX MULTI · tronera amarilla",
    "ruleMultiText": "Casillas elegidas del campo principal reciben ×10. La bola sale de nuevo: debe parar en una casilla mejorada para recibir el premio mayor.",
    "ruleLuckyTitle": "LUCKY SHOT · tronera roja",
    "ruleLuckyText": "La bola cae y sale a uno de dos Campos bonus. Todas sus casillas pagan. También se aplica 10X BOOST.",
    "ruleFieldTitle": "5, 7 o 9 líneas",
    "ruleFieldText": "Cambian el campo y los multiplicadores, no la apuesta por bola. Se eligen entre partidas.",
    "ruleAutoTitle": "Juego automático",
    "ruleAutoText": "Elige lanzamientos y paradas opcionales. Los bonos no cobran otra apuesta. Ocultar el juego lo pausa; al volver continúa. Tras cambiar el tamaño, toca la pantalla.",
    "rulesAboutTitle": "Información útil",
    "rulesAboutIntro": "Multiplicadores sin bonos.",
    "rulesHowToWinTitle": "Grandes premios",
    "rulesHowToWinText": "Desde 10x hay música y destellos, también en morado. Las casillas verdes mejoradas pasan a amarillo desde 1x y rojo desde 10x. Morado indica 10X BOOST.",
    "rulesRtpTitle": "RTP teórico",
    "rulesRtpText": "RTP: 97,45% en todas las líneas, incluidos los bonos. Es la media de muchas apuestas, no una garantía por partida.",
    "rulesMaxWinTitle": "Premio máximo",
    "rulesMaxWinText": "Máximo por bola pagada: 5 líneas — 1.200x con 10X BOOST, luego LUCKY SHOT y 120x en el campo de bono derecho. En 7 / 9 líneas: 6.000x / 8.500x con EX MULTI y 10X BOOST, en cualquier orden, y un acierto en el centro potenciado. Cada bola puede entrar en dos troneras como máximo en total. Las bolas creadas heredan las entradas usadas.",
    "rulesVolatilityTitle": "Bonos y apuestas",
    "rulesVolatilityText": "Los bonos se juegan por turnos; las nuevas apuestas esperan. Los efectos morado y amarillo pueden combinarse. El amarillo solo mejora el campo principal.",
    "rulesDisclosureTitle": "Juego demo",
    "rulesDisclosureText": "Saldo y tablas de jugadores son de demostración. El resultado es aleatorio e independiente del saldo y premios anteriores. La velocidad no cambia los premios.",
    "rulesTab0": "Cómo jugar",
    "rulesTab1": "Bonos",
    "rulesTab2": "Premios",
    "rulesBonusIntro": "Entrar en una tronera activa un bono sin otra apuesta."
  },
  "pt": {
    "balance": "Saldo",
    "changeAvatar": "Avatar",
    "sound": "Sons",
    "music": "Música",
    "animations": "Animações",
    "language": "Idioma",
    "gameRules": "Regras",
    "rules": "Regras",
    "topUpTitle": "Adicionar saldo",
    "topUpText": "Adicione qualquer valor para continuar jogando.",
    "amount": "Valor",
    "topUp": "ADICIONAR",
    "cancel": "CANCELAR",
    "totalHistory": "HISTÓRICO:",
    "roundHistory": "Histórico de rodadas",
    "todayTopWins": "TOP DE HOJE",
    "riskLevel": "RISCO",
    "lines": "LINHAS",
    "low": "Baixo",
    "normal": "Normal",
    "high": "Alto",
    "pucks": "BOLAS",
    "auto": "AUTO",
    "bet": "APOSTAR",
    "wait": "AGUARDE",
    "round": "RODADA",
    "livePlayers": "JOGADORES DO PROTÓTIPO",
    "liveSubtitle": "SIMULAÇÃO LOCAL · MESMA MATEMÁTICA",
    "player": "Jogador",
    "type": "Tipo",
    "riskLines": "Risco / Linhas",
    "result": "Resultado",
    "payout": "Prêmio",
    "status": "Status",
    "lost": "Perdeu",
    "win": "Ganho",
    "avatar": "Avatar",
    "showFullWinners": "Mostrar os 10 maiores ganhos de hoje",
    "showTopWinner": "Mostrar apenas o maior ganho de hoje",
    "settings": "Configurações",
    "volume": "Volume",
    "audioSection": "Áudio",
    "playSection": "Jogo",
    "profileSection": "Perfil e idioma",
    "moreSection": "Mais",
    "quickPlay": "Jogo rápido",
    "quickHint": "Bolas mais rápidas e apostas repetidas mais frequentes.",
    "openHistory": "Meus lançamentos",
    "openTop": "Top do dia",
    "changeNickname": "Apelido",
    "yourNickname": "Seu apelido",
    "nicknameHint": "1–20 caracteres. Visível no top do dia.",
    "nicknameRequired": "Digite um apelido",
    "save": "Salvar",
    "done": "Pronto",
    "betPerBall": "Aposta por bola · USD",
    "totalBet": "Aposta total",
    "launchBall": "Lançar uma bola",
    "controls": "Controles do jogo",
    "autoCount": "Lançamentos pagos",
    "autoHint": "O botão ■ para novas apostas. As bolas em jogo terminam.",
    "startAuto": "Iniciar jogo automático",
    "noHistory": "Ainda não há lançamentos concluídos",
    "close": "Fechar",
    "time": "Hora",
    "profit": "Resultado líquido",
    "demoWins": "Prêmios · DEMO",
    "backToGame": "Voltar ao jogo",
    "collapse": "Recolher",
    "expand": "Expandir",
    "bonusHelpLabel": "Como funciona este bônus",
    "bonusDemo": "Ver exemplo",
    "demoNote": "Exemplo, não prêmio garantido",
    "pauseDemo": "Pausa",
    "playDemo": "Repetir",
    "stepCapture": "Entrada",
    "stepPrepare": "Bônus",
    "stepRelease": "Prêmio",
    "colorsTitle": "Cores dos multiplicadores",
    "greenLabel": "Verde · até 1x",
    "yellowLabel": "Amarelo · acima de 1x e abaixo de 10x",
    "redLabel": "Vermelho · a partir de 10x",
    "purpleLabel": "Roxo · 10X BOOST",
    "multiplierTable": "Multiplicadores atuais",
    "mainField": "Campo principal",
    "leftRoom": "Campo bônus esquerdo",
    "rightRoom": "Campo bônus direito",
    "loading": "Carregando Balloro X",
    "fieldLabel": "Campo de jogo de Balloro X",
    "ruleLaunchTitle": "Lance as bolas",
    "ruleLaunchText": "Escolha aposta por bola, 1–3 bolas e 5, 7 ou 9 linhas. Pressione SPIN. Manter pressionado repete apostas.",
    "ruleWinsTitle": "Parada e prêmio",
    "ruleWinsText": "Aposta por bola × multiplicador da casa final. Os prêmios se somam. Menos que a aposta é retorno parcial, não lucro.",
    "rulePocketTitle": "3X BALLS · caçapa verde",
    "rulePocketFieldText": "Três bolas substituem uma. Seus prêmios se somam. Sem aposta adicional.",
    "ruleBoostTitle": "10X BOOST · caçapa roxa",
    "ruleBoostText": "Os campos principal e bônus passam a ×10 para esta bola e as que ela gera. Outra entrada roxa prolonga o efeito, sem multiplicá-lo novamente.",
    "ruleMultiTitle": "EX MULTI · caçapa amarela",
    "ruleMultiText": "Casas escolhidas do campo principal recebem ×10. A bola sai novamente: precisa parar numa casa melhorada para receber o prêmio maior.",
    "ruleLuckyTitle": "LUCKY SHOT · caçapa vermelha",
    "ruleLuckyText": "A bola cai e sai para um de dois Campos bônus. Todas as casas pagam. 10X BOOST também se aplica.",
    "ruleFieldTitle": "5, 7 ou 9 linhas",
    "ruleFieldText": "Mudam o campo e os multiplicadores, não a aposta por bola. Escolha entre partidas.",
    "ruleAutoTitle": "Jogo automático",
    "ruleAutoText": "Escolha lançamentos e paradas opcionais. Bônus não cobram nova aposta. Ocultar o jogo pausa; ao voltar continua. Após redimensionar, toque na tela.",
    "rulesAboutTitle": "Informações úteis",
    "rulesAboutIntro": "Multiplicadores sem bônus.",
    "rulesHowToWinTitle": "Grandes prêmios",
    "rulesHowToWinText": "Desde 10x há música e flashes, inclusive em roxo. Casas verdes melhoradas ficam amarelas desde 1x e vermelhas desde 10x. Roxo indica 10X BOOST.",
    "rulesRtpTitle": "RTP teórico",
    "rulesRtpText": "RTP: 97,45% em todas as linhas, incluindo bônus. É a média de muitas apostas, não uma garantia por partida.",
    "rulesMaxWinTitle": "Prêmio máximo",
    "rulesMaxWinText": "Máximo por bola paga: 5 linhas — 1.200x com 10X BOOST, depois LUCKY SHOT e 120x no campo de bônus direito. Em 7 / 9 linhas: 6.000x / 8.500x com EX MULTI e 10X BOOST, em qualquer ordem, e acerto no centro ampliado. Cada bola pode entrar em no máximo duas caçapas no total. As bolas criadas herdam as entradas usadas.",
    "rulesVolatilityTitle": "Bônus e apostas",
    "rulesVolatilityText": "Bônus jogam por turnos; novas apostas aguardam. Efeitos roxo e amarelo podem combinar. O amarelo só melhora o campo principal.",
    "rulesDisclosureTitle": "Jogo demo",
    "rulesDisclosureText": "Saldo e tabelas de jogadores são demonstrativos. O resultado é aleatório e independe do saldo ou prêmios anteriores. A velocidade não altera os prêmios.",
    "rulesTab0": "Como jogar",
    "rulesTab1": "Bônus",
    "rulesTab2": "Prêmios",
    "rulesBonusIntro": "Entrar numa caçapa ativa um bônus sem nova aposta."
  },
  "de": {
    "balance": "Guthaben",
    "changeAvatar": "Avatar",
    "sound": "Töne",
    "music": "Musik",
    "animations": "Animationen",
    "language": "Sprache",
    "gameRules": "Regeln",
    "rules": "Regeln",
    "topUpTitle": "Guthaben aufladen",
    "topUpText": "Füge einen beliebigen Betrag hinzu, um weiterzuspielen.",
    "amount": "Betrag",
    "topUp": "AUFLADEN",
    "cancel": "ABBRECHEN",
    "totalHistory": "VERLAUF:",
    "roundHistory": "Rundenverlauf",
    "todayTopWins": "TOP HEUTE",
    "riskLevel": "RISIKO",
    "lines": "LINIEN",
    "low": "Niedrig",
    "normal": "Normal",
    "high": "Hoch",
    "pucks": "BÄLLE",
    "auto": "AUTO",
    "bet": "SETZEN",
    "wait": "WARTEN",
    "round": "RUNDE",
    "livePlayers": "LIVE-PROTOTYP-SPIELER",
    "liveSubtitle": "LOKALE SIMULATION · GEMEINSAME MATHEMATIK",
    "player": "Spieler",
    "type": "Typ",
    "riskLines": "Risiko / Linien",
    "result": "Ergebnis",
    "payout": "Auszahlung",
    "status": "Status",
    "lost": "Verloren",
    "win": "Gewinn",
    "avatar": "Avatar",
    "showFullWinners": "Heutige Top 10 anzeigen",
    "showTopWinner": "Nur heutigen Top-Gewinn anzeigen",
    "settings": "Einstellungen",
    "volume": "Lautstärke",
    "audioSection": "Audio",
    "playSection": "Spiel",
    "profileSection": "Profil & Sprache",
    "moreSection": "Mehr",
    "quickPlay": "Schnelles Spiel",
    "quickHint": "Schnellere Bälle und häufigere wiederholte Einsätze.",
    "openHistory": "Meine Würfe",
    "openTop": "Tages-Top",
    "changeNickname": "Spielername",
    "yourNickname": "Dein Spitzname",
    "nicknameHint": "1–20 Zeichen. Im Tages-Top sichtbar.",
    "nicknameRequired": "Spitznamen eingeben",
    "save": "Speichern",
    "done": "Fertig",
    "betPerBall": "Einsatz pro Ball · USD",
    "totalBet": "Gesamteinsatz",
    "launchBall": "Einen Ball starten",
    "controls": "Spielsteuerung",
    "autoCount": "Bezahlte Würfe",
    "autoHint": "Die Taste ■ stoppt neue Einsätze. Laufende Bälle beenden ihr Spiel.",
    "startAuto": "Autoplay starten",
    "noHistory": "Noch keine abgeschlossenen Würfe",
    "close": "Schließen",
    "time": "Zeit",
    "profit": "Nettoergebnis",
    "demoWins": "Gewinne · DEMO",
    "backToGame": "Zurück zum Spiel",
    "collapse": "Einklappen",
    "expand": "Ausklappen",
    "bonusHelpLabel": "So funktioniert dieser Bonus",
    "bonusDemo": "Beispiel ansehen",
    "demoNote": "Beispiel, kein garantierter Gewinn",
    "pauseDemo": "Pause",
    "playDemo": "Wiederholen",
    "stepCapture": "Treffer",
    "stepPrepare": "Bonus",
    "stepRelease": "Auszahlung",
    "colorsTitle": "Multiplikatorfarben",
    "greenLabel": "Grün · bis 1x",
    "yellowLabel": "Gelb · über 1x, unter 10x",
    "redLabel": "Rot · ab 10x",
    "purpleLabel": "Violett · 10X BOOST",
    "multiplierTable": "Aktuelle Multiplikatoren",
    "mainField": "Hauptfeld",
    "leftRoom": "Linkes Bonusfeld",
    "rightRoom": "Rechtes Bonusfeld",
    "loading": "Balloro X wird geladen",
    "fieldLabel": "Balloro-X-Spielfeld",
    "ruleLaunchTitle": "Bälle starten",
    "ruleLaunchText": "Einsatz pro Ball, 1–3 Bälle und 5, 7 oder 9 Linien wählen. SPIN drücken. Gedrückthalten wiederholt Einsätze.",
    "ruleWinsTitle": "Stopp und Auszahlung",
    "ruleWinsText": "Einsatz pro Ball × Multiplikator der Stoppzelle. Alle Auszahlungen werden addiert. Weniger als der Einsatz ist eine Teilrückzahlung, kein Gewinn.",
    "rulePocketTitle": "3X BALLS · grüne Tasche",
    "rulePocketFieldText": "Drei Bälle ersetzen einen. Ihre Auszahlungen werden addiert. Kein zusätzlicher Einsatz.",
    "ruleBoostTitle": "10X BOOST · violette Tasche",
    "ruleBoostText": "Haupt- und Bonusfelder erhalten ×10 für diesen Ball und die daraus entstehenden Bälle. Ein weiterer violetter Treffer verlängert den Effekt, ohne erneut zu multiplizieren.",
    "ruleMultiTitle": "EX MULTI · gelbe Tasche",
    "ruleMultiText": "Ausgewählte Hauptfeld-Zellen erhalten ×10. Der Ball startet erneut: Für die höhere Auszahlung muss er in einer verstärkten Zelle stoppen.",
    "ruleLuckyTitle": "LUCKY SHOT · rote Tasche",
    "ruleLuckyText": "Der Ball sinkt ab und startet in einem von zwei Bonusfeldern. Jede Zelle zahlt. Auch 10X BOOST gilt hier.",
    "ruleFieldTitle": "5, 7 oder 9 Linien",
    "ruleFieldText": "Linien ändern Feld und Multiplikatoren, nicht den Einsatz pro Ball. Auswahl zwischen Spielen.",
    "ruleAutoTitle": "Autoplay",
    "ruleAutoText": "Wurfzahl und optionale Stopps wählen. Boni kosten keinen neuen Einsatz. Ausblenden pausiert, Rückkehr setzt fort. Nach Größenänderung auf den Bildschirm tippen.",
    "rulesAboutTitle": "Gut zu wissen",
    "rulesAboutIntro": "Multiplikatoren ohne Boni.",
    "rulesHowToWinTitle": "Große Gewinne",
    "rulesHowToWinText": "Ab 10x gibt es Musik und Blinken, auch in Violett. Verstärkte grüne Zellen werden ab 1x gelb und ab 10x rot. Violett bedeutet 10X BOOST.",
    "rulesRtpTitle": "Theoretischer RTP",
    "rulesRtpText": "RTP: 97,45% auf allen Linien, einschließlich Boni. Durchschnitt vieler Einsätze, keine Garantie für ein Spiel.",
    "rulesMaxWinTitle": "Maximaler Gewinn",
    "rulesMaxWinText": "Maximum pro bezahltem Ball: 5 Linien — 1.200x mit 10X BOOST, danach LUCKY SHOT und 120x im rechten Bonusfeld. Bei 7 / 9 Linien: 6.000x / 8.500x mit EX MULTI und 10X BOOST in beliebiger Reihenfolge, danach ein Treffer im verstärkten Zentrum. Insgesamt höchstens zwei Tascheneintritte pro Ball. Erzeugte Bälle übernehmen die verwendeten Eintritte.",
    "rulesVolatilityTitle": "Boni und Einsätze",
    "rulesVolatilityText": "Boni laufen nacheinander; neue Einsätze warten. Violette und gelbe Effekte können zusammenwirken. Gelb verstärkt nur das Hauptfeld.",
    "rulesDisclosureTitle": "Demo-Spiel",
    "rulesDisclosureText": "Guthaben und Spielertabellen sind Demonstrationen. Ergebnisse sind zufällig, unabhängig von Guthaben und früheren Gewinnen. Spieltempo ändert keine Auszahlungen.",
    "rulesTab0": "So geht’s",
    "rulesTab1": "Boni",
    "rulesTab2": "Auszahlungen",
    "rulesBonusIntro": "Ein Treffer in einer Tasche startet einen Bonus ohne neuen Einsatz."
  },
  "fr": {
    "balance": "Solde",
    "changeAvatar": "Avatar",
    "sound": "Sons",
    "music": "Musique",
    "animations": "Animations",
    "language": "Langue",
    "gameRules": "Règles",
    "rules": "Règles",
    "topUpTitle": "Recharger le solde",
    "topUpText": "Ajoutez le montant de votre choix pour continuer.",
    "amount": "Montant",
    "topUp": "RECHARGER",
    "cancel": "ANNULER",
    "totalHistory": "HISTORIQUE :",
    "roundHistory": "Historique des manches",
    "todayTopWins": "TOP DU JOUR",
    "riskLevel": "RISQUE",
    "lines": "LIGNES",
    "low": "Faible",
    "normal": "Normal",
    "high": "Élevé",
    "pucks": "BOULES",
    "auto": "AUTO",
    "bet": "MISER",
    "wait": "ATTENDRE",
    "round": "MANCHE",
    "livePlayers": "JOUEURS DU PROTOTYPE",
    "liveSubtitle": "SIMULATION LOCALE · MÊMES MATHÉMATIQUES",
    "player": "Joueur",
    "type": "Type",
    "riskLines": "Risque / Lignes",
    "result": "Résultat",
    "payout": "Gain",
    "status": "Statut",
    "lost": "Perdu",
    "win": "Gain",
    "avatar": "Avatar",
    "showFullWinners": "Afficher les 10 meilleurs gains du jour",
    "showTopWinner": "Afficher uniquement le meilleur gain du jour",
    "settings": "Réglages",
    "volume": "Volume",
    "audioSection": "Audio",
    "playSection": "Jeu",
    "profileSection": "Profil et langue",
    "moreSection": "Plus",
    "quickPlay": "Jeu rapide",
    "quickHint": "Boules plus rapides et mises répétées plus fréquentes.",
    "openHistory": "Mes lancers",
    "openTop": "Top du jour",
    "changeNickname": "Pseudo",
    "yourNickname": "Votre pseudo",
    "nicknameHint": "1–20 caractères. Visible dans le top du jour.",
    "nicknameRequired": "Saisissez un pseudo",
    "save": "Enregistrer",
    "done": "Terminé",
    "betPerBall": "Mise par boule · USD",
    "totalBet": "Mise totale",
    "launchBall": "Lancer une boule",
    "controls": "Commandes du jeu",
    "autoCount": "Lancers payants",
    "autoHint": "Le bouton ■ arrête les nouvelles mises. Les boules en jeu terminent.",
    "startAuto": "Démarrer le jeu automatique",
    "noHistory": "Aucun lancer terminé",
    "close": "Fermer",
    "time": "Heure",
    "profit": "Résultat net",
    "demoWins": "Gains · DÉMO",
    "backToGame": "Revenir au jeu",
    "collapse": "Réduire",
    "expand": "Développer",
    "bonusHelpLabel": "Fonctionnement du bonus",
    "bonusDemo": "Voir un exemple",
    "demoNote": "Exemple, pas de gain garanti",
    "pauseDemo": "Pause",
    "playDemo": "Rejouer",
    "stepCapture": "Entrée",
    "stepPrepare": "Bonus",
    "stepRelease": "Gain",
    "colorsTitle": "Couleurs des multiplicateurs",
    "greenLabel": "Vert · jusqu’à 1x",
    "yellowLabel": "Jaune · plus de 1x, moins de 10x",
    "redLabel": "Rouge · à partir de 10x",
    "purpleLabel": "Violet · 10X BOOST",
    "multiplierTable": "Multiplicateurs actuels",
    "mainField": "Terrain principal",
    "leftRoom": "Terrain bonus gauche",
    "rightRoom": "Terrain bonus droit",
    "loading": "Chargement de Balloro X",
    "fieldLabel": "Terrain de jeu Balloro X",
    "ruleLaunchTitle": "Lancez les boules",
    "ruleLaunchText": "Choisissez une mise par boule, 1–3 boules et 5, 7 ou 9 lignes. Appuyez sur SPIN. Le maintenir répète les mises.",
    "ruleWinsTitle": "Arrêt et gain",
    "ruleWinsText": "Mise par boule × multiplicateur de sa case finale. Les gains s’additionnent. Moins que la mise est un retour partiel, pas un bénéfice.",
    "rulePocketTitle": "3X BALLS · poche verte",
    "rulePocketFieldText": "Trois boules remplacent une. Leurs gains s’additionnent. Sans mise supplémentaire.",
    "ruleBoostTitle": "10X BOOST · poche violette",
    "ruleBoostText": "Les terrains principal et bonus passent à ×10 pour cette boule et celles qu’elle crée. Une autre entrée violette prolonge l’effet, sans le multiplier à nouveau.",
    "ruleMultiTitle": "EX MULTI · poche jaune",
    "ruleMultiText": "Des cases choisies du terrain principal reçoivent ×10. La boule repart : elle doit s’arrêter sur une case améliorée pour le gain supérieur.",
    "ruleLuckyTitle": "LUCKY SHOT · poche rouge",
    "ruleLuckyText": "La boule s’enfonce puis part sur l’un des deux Terrains bonus. Toutes leurs cases paient. 10X BOOST s’applique aussi.",
    "ruleFieldTitle": "5, 7 ou 9 lignes",
    "ruleFieldText": "Modifient le terrain et les multiplicateurs, pas la mise par boule. À choisir entre les parties.",
    "ruleAutoTitle": "Jeu automatique",
    "ruleAutoText": "Choisissez des lancers et des arrêts facultatifs. Les bonus ne coûtent pas de nouvelle mise. Masquer le jeu le met en pause, revenir le reprend. Après redimensionnement, touchez l’écran.",
    "rulesAboutTitle": "À savoir",
    "rulesAboutIntro": "Multiplicateurs sans bonus.",
    "rulesHowToWinTitle": "Gros gains",
    "rulesHowToWinText": "Dès 10x, musique et clignotement, même en violet. Les cases vertes améliorées deviennent jaunes dès 1x et rouges dès 10x. Violet signifie 10X BOOST.",
    "rulesRtpTitle": "RTP théorique",
    "rulesRtpText": "RTP : 97,45% sur toutes les lignes, bonus inclus. Moyenne de nombreuses mises, pas une garantie pour une partie.",
    "rulesMaxWinTitle": "Gain maximal",
    "rulesMaxWinText": "Maximum par boule payante : 5 lignes — 1 200x avec 10X BOOST, puis LUCKY SHOT et 120x sur le champ bonus droit. Sur 7 / 9 lignes : 6 000x / 8 500x avec EX MULTI et 10X BOOST dans l’un ou l’autre ordre, puis un arrêt au centre renforcé. Deux entrées dans les poches au maximum au total. Les boules créées héritent des entrées utilisées.",
    "rulesVolatilityTitle": "Bonus et mises",
    "rulesVolatilityText": "Les bonus passent à tour de rôle ; les nouvelles mises attendent. Violet et jaune peuvent se combiner. Jaune n’améliore que le terrain principal.",
    "rulesDisclosureTitle": "Jeu démo",
    "rulesDisclosureText": "Le solde et les tableaux des joueurs sont démonstratifs. Le résultat est aléatoire, indépendant du solde et des gains passés. La vitesse ne change pas les gains.",
    "rulesTab0": "Comment jouer",
    "rulesTab1": "Bonus",
    "rulesTab2": "Gains",
    "rulesBonusIntro": "Entrer dans une poche active un bonus sans nouvelle mise."
  }
};
